import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ChevronLeft } from 'lucide-react';
import { LogoMark } from '../components/Logo';

const COMPANY = 'FitFlow, Inc.';
const COMPANY_ADDRESS = '[REPLACE WITH REGISTERED BUSINESS ADDRESS]';
const GOVERNING_LAW = '[REPLACE — e.g. State of Delaware, USA]';
const ARBITRATION_VENUE = '[REPLACE — e.g. American Arbitration Association]';
const LEGAL_EMAIL = 'fitflow2000@gmail.com';
const LAST_UPDATED = '2026-06-15';

export const Terms: React.FC = () => {
  const navigate = useNavigate();
  return (
    <div className="pb-24 pt-4 px-5 min-h-screen max-w-2xl mx-auto">
      <header className="flex items-center gap-3 pt-2 mb-6">
        <button onClick={() => navigate(-1)} className="w-10 h-10 glass rounded-xl flex items-center justify-center text-text-dim hover:text-white" aria-label="Back">
          <ChevronLeft size={18} />
        </button>
        <LogoMark size={28} />
        <h1 className="font-display text-2xl font-bold text-white tracking-tight">Terms of Service</h1>
      </header>

      <article className="space-y-5 text-white/80 text-sm leading-relaxed">
        <p className="text-text-dim text-xs">Last updated: {LAST_UPDATED}</p>

        <p>
          These Terms of Service ("Terms") govern your use of the FitFlow
          applications and services provided by {COMPANY} ("we", "us"). By
          creating an account or using the Service you agree to these Terms.
        </p>

        <Section title="1. Not medical advice">
          <p className="font-medium text-white">
            FitFlow provides general fitness, nutrition, and recovery guidance
            for healthy adults. It is NOT medical advice. AI-generated content
            (form check, meal plans, workout plans, weekly recaps) is best-effort
            and may be inaccurate. Consult a qualified healthcare professional
            before starting any new exercise or nutrition program, especially if
            you have a medical condition, are pregnant, or take medication.
            If you experience pain, dizziness, or shortness of breath, stop
            immediately and seek medical attention.
          </p>
        </Section>

        <Section title="2. Eligibility">
          <List items={[
            'You must be at least 13 years old.',
            'If you are between 13 and 18, you must have a parent or guardian agree to these Terms on your behalf where required by your local law.',
            'You must have the legal capacity to enter into a contract.',
            'You must not be barred from using the Service under applicable law.',
          ]} />
        </Section>

        <Section title="3. Your account">
          <List items={[
            'You are responsible for the security of your account credentials.',
            'You may not share your account, sell it, or let others use it.',
            'Notify us immediately if you suspect unauthorized access.',
            'We may suspend or terminate accounts that violate these Terms.',
          ]} />
        </Section>

        <Section title="4. Acceptable use">
          <p>You agree not to:</p>
          <List items={[
            'Harass, threaten, defame, or harm other users in posts, comments, or community features.',
            'Post content that is unlawful, infringing, sexually explicit, hateful, or violent.',
            'Reverse engineer, decompile, scrape, or attempt to disrupt the Service.',
            'Use the Service to build a competing product or train AI models.',
            'Upload malware, run automated bots, or perform load tests without our written consent.',
            'Impersonate another person or misrepresent your affiliation.',
          ]} />
          <p>
            We may remove content and terminate accounts that violate these rules.
          </p>
        </Section>

        <Section title="5. User content">
          <p>
            You retain ownership of content you post (workouts, comments, photos).
            By posting you grant {COMPANY} a worldwide, non-exclusive, royalty-free
            license to host, display, reproduce, and adapt your content solely to
            operate and improve the Service. You can delete content at any time;
            backup and log copies may persist for up to 30 days.
          </p>
        </Section>

        <Section title="6. AI features">
          <p>
            Form Check, workout plans, meal plans, weekly recaps, and other AI
            output are generated by Google Gemini. Output:
          </p>
          <List items={[
            'Can be inaccurate, biased, or unsafe — always use your judgment.',
            'Is generated based on the inputs you provide and your stored profile.',
            'Should not be relied on as professional advice.',
            'May vary between users and over time.',
          ]} />
        </Section>

        <Section title="7. Subscriptions and refunds">
          <List items={[
            'FitFlow Pro is a recurring subscription billed monthly ($4.99) or yearly ($60.10) via Stripe (web) or the platform store (mobile).',
            'New accounts include a 6-day free trial that requires no credit card and never auto-charges. When the trial ends, your account simply reverts to the free tier unless you choose to subscribe.',
            'Cancel at any time in Settings or your platform store; cancellation takes effect at the end of the current paid billing period.',
            'Refunds: we generally do not offer prorated refunds. EU/UK users have statutory withdrawal rights as required by law.',
            'Pricing may change with at least 14 days notice for active subscribers.',
          ]} />
        </Section>

        <Section title="8. Intellectual property">
          <p>
            The Service, including software, design, brand, and content (excluding
            user content), is owned by {COMPANY} and protected by copyright,
            trademark, and other laws. You may not copy or use our marks without
            written permission.
          </p>
        </Section>

        <Section title="9. Third-party services">
          <p>
            The Service integrates with Firebase, Google Gemini, Stripe, Health
            Connect, Apple Health, Google Fit, and OpenFoodFacts. Your use of
            those services is governed by their own terms; we are not responsible
            for them.
          </p>
        </Section>

        <Section title="10. Disclaimers">
          <p className="uppercase tracking-wide text-white/90 text-xs">
            The Service is provided "as is" and "as available" without warranties
            of any kind, express or implied, including merchantability, fitness
            for a particular purpose, and non-infringement, to the maximum extent
            permitted by law.
          </p>
        </Section>

        <Section title="11. Limitation of liability">
          <p className="uppercase tracking-wide text-white/90 text-xs">
            To the maximum extent permitted by law, {COMPANY} and its officers,
            employees, and affiliates will not be liable for indirect, incidental,
            special, consequential, or punitive damages, or for any loss of profits,
            data, goodwill, or other intangible losses arising out of your use of
            the Service. Our total liability for any claim is capped at the greater
            of (a) the amount you paid us in the 12 months before the claim and
            (b) USD $100.
          </p>
          <p>
            Nothing in these Terms excludes liability that cannot lawfully be
            excluded (such as for death, personal injury caused by negligence,
            fraud, or under consumer-protection statutes).
          </p>
        </Section>

        <Section title="12. Indemnification">
          <p>
            You agree to indemnify and hold harmless {COMPANY} from claims arising
            out of your content, your breach of these Terms, or your violation of
            applicable law.
          </p>
        </Section>

        <Section title="13. Governing law and disputes">
          <p>
            These Terms are governed by the laws of {GOVERNING_LAW}, without regard
            to conflict-of-laws principles. Any dispute will be resolved by binding
            arbitration administered by {ARBITRATION_VENUE}, except where you opt
            out within 30 days of accepting these Terms or where the dispute may
            be brought in small-claims court. You and {COMPANY} agree to resolve
            disputes individually and waive class-action rights to the extent
            permitted by law.
          </p>
        </Section>

        <Section title="14. Changes to these Terms">
          <p>
            We may update these Terms. Material changes will be announced at least
            14 days in advance. Continued use after the effective date means you
            accept the updated Terms.
          </p>
        </Section>

        <Section title="15. Contact">
          <p>
            {COMPANY}<br/>
            {COMPANY_ADDRESS}<br/>
            <a href={`mailto:${LEGAL_EMAIL}`} className="text-accent">{LEGAL_EMAIL}</a>
          </p>
        </Section>
      </article>
    </div>
  );
};

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <section className="space-y-2">
    <h2 className="font-display text-lg font-bold text-white tracking-tight">{title}</h2>
    {children}
  </section>
);

const List: React.FC<{ items: string[] }> = ({ items }) => (
  <ul className="space-y-1.5 pl-4">
    {items.map((item, i) => (
      <li key={i} className="relative">
        <span className="absolute -left-4 top-2 w-1.5 h-1.5 rounded-full bg-accent" />
        {item}
      </li>
    ))}
  </ul>
);
